let tableList = ['kanna', 'tinker', 'sniper', 'lycan', 'axe', 'luna', 'beastmaster', 'omniknight', 'bristleback', 'timbersaw', 'earthshaker', 'enchantress', 'venomancer', 
'zeus',
'chen',
'mazzie',
'prellex',
'bloodseeker',
'sven',
'ursa',
'magnus',
'necrophos',
'abaddon',
'viper',
'lion',
'tidehunter',
'pugna',
'meepo',
'rix',
'crystal maiden',
'storm spirit',
'dark seer',
'centaur warrunner',
'skywrath mage',
'winter wyvern',
'bounty hunter',
'phantom assassin',
'treant protector',
'ogre magi',
'sorla khan',
'legion commander',
'drow ranger'];

module.exports = tableList
