let tableList = ['kanna', 
'tinker', 
'sniper', 
'lycan', 
'axe', 
'luna', 
'beastmaster', 
'omniknight', 'bristleback', 'timbersaw', 'earthshaker', 'enchantress',
 'venomancer', 
'zeus',
'chen',
'mazzie',
'prellex',
'bloodseeker',
'sven',
'ursa',
'magnus',
'necrophos',
'abaddon',
'viper',
'lion',
'tidehunter',
'pugna',
'meepo',
'rix',
'crystal_maiden',
'storm_spirit',
'dark_seer',
'centaur_warrunner',
'skywrath_mage',
'winter_wyvern',
'bounty_hunter',
'phantom_assassin',
'treant_protector',
'ogre_magi',
'sorla_khan',
'legion_commander',
'drow_ranger',
'lich'];

module.exports = tableList
